retargeting:
  type: DexPilot
  urdf_path: omni_hand/omni_hand_right.urdf

  # target_joint_names: null
  target_joint_names: [ 'thumb_cmc_roll', 'thumb_cmc_yaw', 'thumb_cmc_pitch', 'thumb_mcp',
                        'index_mcp_roll', 'index_mcp_pitch', 'index_pip', 
                        'middle_mcp_roll', 'middle_mcp_pitch', 'middle_pip', 
                        'ring_mcp_pitch', 
                        'pinky_mcp_pitch']
  
  wrist_link_name: "hand_base_link"

  finger_tip_link_names: [ "thumb_distal",  "index_distal", "middle_distal", "ring_distal", "pinky_distal" ]
  
  scaling_factor: 0.8 # 1.4 for mano to omni, 0.8 for shadow to omni
  
  # A smaller alpha means stronger filtering, i.e. more smooth but also larger latency
  low_pass_alpha: 1
