retargeting:
  type: position
  urdf_path: omni_hand/omni_hand_right.urdf

  # target_joint_names: null
  target_joint_names: [ 'thumb_cmc_roll', 'thumb_cmc_yaw', 'thumb_cmc_pitch', 'thumb_mcp', 'thumb_ip', 
                        'index_mcp_roll', 'index_mcp_pitch', 'index_pip', 'index_dip', 
                        'middle_mcp_roll', 'middle_mcp_pitch', 'middle_pip', 'middle_dip', 
                        'ring_mcp_pitch', 'ring_pip', 'ring_dip', 
                        'pinky_mcp_pitch', 'pinky_pip', 'pinky_dip' ]
  target_link_names: [ "thumb_distal",  "index_distal", "middle_distal", "ring_distal", "pinky_distal",
                       "thumb_proximal",  "index_middle", "middle_middle", "ring_middle", "pinky_middle" ]
  # target_link_names: [ "thumb_tip",  "index_tip"]

  target_link_human_indices: [ 4, 8, 12, 16, 20, 2, 6, 10, 14, 18 ]
  # target_link_human_indices: [ 4, 8, ]
  add_dummy_free_joint: True

  # A smaller alpha means stronger filtering, i.e. more smooth but also larger latency
  # 1 means no filter while 0 means not moving
  low_pass_alpha: 1

  # To ignore the mimic joint tags in the URDF, set it to True
  ignore_mimic_joint: False
